baseURL = 'https://example.org/'
title = 'Sky Theme'
defaultContentLanguage = "es"

removePathAccents = true
summaryLength = 3

ignoreFiles = ['^banners/']

[outputs]
  home = ["html", "json"]

[taxonomies]
  category = "categories"
  author = "authors"
  destino = "destino"

[build]
  [build.buildStats]
    enable = true

  [[build.cachebusters]]
    source = "layouts/.*"
    target = "css"

  [[build.cachebusters]]
    source = "assets/js/.*"
    target = "css"

  [[build.cachebusters]]
    source = "assets/notwatching/hugo_stats\\.json"
    target = "css"


[module]
  # imports
  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/jslibs/preact-bundle'

  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/jslibs/alpinejs'

  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/jslibs/minisearch'

  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/adroller'

  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/imgproxy'

  [[module.imports]]
    path = "github.com/etheriamagazine/hugo-modules/seo-tools/basic-seo"

  [[module.imports]]
    path = "github.com/etheriamagazine/hugo-modules/seo-tools/plausible-analytics"

  [[module.imports]]
    path = "github.com/etheriamagazine/hugo-modules/seo-tools/json-ld"
