baseURL = 'https://example.org/'
title = 'Sky Theme'
defaultContentLanguage = "es"

removePathAccents = true
summaryLength = 3
enableEmoji = true
enableGitInfo = true
ignoreFiles = ['^banners/']

[frontmatter]
  lastmod = ['lastmod', 'modified', 'date', 'publishDate', 'pubdate']

[minify]
  minifyOutput = true
  [minify.tdewolff.html]
    keepQuotes = true

[outputs]
  home = ['html']
  page = ['html']
  rss = ['rss']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[taxonomies]
  category = "categories"
  author = "authors"
  destino = "destino"

[permalinks]
  [permalinks.page]
    posts = "/articulos/:filename"

  [permalinks.taxonomy]
    categories = "/categorias"
    authors = "/autoras"

  [permalinks.term]
    categories = "/:slug"
    authors = "/autoras/:slug"


[related]
  includeNewer = true
  threshold = 80
  toLower = true

  [[related.indices]]
    name = 'authors'
    weight = 2
  [[related.indices]]
    name = 'categories'
    weight = 1


[build]
  noJSConfigInAssets = true
  [build.buildStats]
    enable = true

  [[build.cachebusters]]
    source = "layouts/.*"
    target = "css"

  [[build.cachebusters]]
    source = "assets/js/.*"
    target = "css"

  [[build.cachebusters]]
    source = "layouts/categories/term.html"
    target = "categories"

  [[build.cachebusters]]
    source = "assets/notwatching/hugo_stats\\.json"
    target = "css"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github-ascii"
      wrapStandAloneImageWithinParagraph = false


[module]
  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/jslibs/preact-bundle'

  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/jslibs/alpinejs'

  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/jslibs/a11y-dialog'

  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/imgproxy'

  [[module.imports]]
    path = "github.com/etheriamagazine/hugo-modules/seo-tools/basic-seo"

  [[module.imports]]
    path = "github.com/etheriamagazine/hugo-modules/seo-tools/plausible-analytics"

  [[module.imports]]
    path = "github.com/etheriamagazine/hugo-modules/seo-tools/json-ld"


[menu]
  # main-100: Viajar Sola
  [[menu.main]]
    name = 'Viajar sola'
    identifier = 'main-100'
    pageRef = 'categories/viajar-sola'
    weight = 1

  [[menu.main]]
    name = 'España'
    identifier = 'main-100/1'
    pageRef = 'categories/viajar-sola/españa'
    parent = 'main-100'
    weight = 1

  [[menu.main]]
    name = 'Europa'
    identifier = 'main-100/2'
    pageRef = 'categories/viajar-sola/europa'
    parent = 'main-100'
    weight = 2

  [[menu.main]]
    name = 'Mundo'
    identifier = 'main-100/3'
    pageRef = 'categories/viajar-sola/mundo'
    parent = 'main-100'
    weight = 3


  # main-200: Viajar con amigas
  [[menu.main]]
    name = 'Viajar con amigas'
    identifier = 'main-200'
    pageRef = 'categories/viajar-con-amigas'
    weight = 2

  [[menu.main]]
    name = 'España'
    identifier = 'main-200/1'
    pageRef = 'categories/viajar-con-amigas/españa'
    parent = 'main-200'
    weight = 1

  [[menu.main]]
    name = 'Europa'
    identifier = 'main-200/2'
    pageRef = 'categories/viajar-con-amigas/europa'
    parent = 'main-200'
    weight = 2

  [[menu.main]]
    name = 'Mundo'
    identifier = 'main-200/3'
    pageRef = 'categories/viajar-con-amigas/mundo'
    parent = 'main-200'
    weight = 3

  # main-300: Viajar en familia
  [[menu.main]]
    name = 'Viajar en familia'
    identifier = 'main-300'
    pageRef = 'categories/viajar-en-familia'
    weight = 3

  [[menu.main]]
    name = 'España'
    identifier = 'main-300/1'
    pageRef = 'categories/viajar-en-familia/españa'
    parent = 'main-300'
    weight = 1

  [[menu.main]]
    name = 'Europa'
    identifier = 'main-300/2'
    pageRef = 'categories/viajar-en-familia/europa'
    parent = 'main-300'
    weight = 2

  [[menu.main]]
    name = 'Mundo'
    identifier = 'main-300/3'
    pageRef = 'categories/viajar-en-familia/mundo'
    parent = 'main-300'
    weight = 3

  # main-400: Viajar en pareja
  [[menu.main]]
    name = 'Viajar en pareja'
    identifier = 'main-400'
    pageRef = 'categories/viajar-en-pareja'
    weight = 4

  [[menu.main]]
    name = 'España'
    identifier = 'main-400/1'
    pageRef = 'categories/viajar-en-pareja/españa'
    parent = 'main-400'
    weight = 1

  [[menu.main]]
    name = 'Europa'
    identifier = 'main-400/2'
    pageRef = 'categories/viajar-en-pareja/europa'
    parent = 'main-400'
    weight = 2

  [[menu.main]]
    name = 'Mundo'
    identifier = 'main-400/3'
    pageRef = 'categories/viajar-en-pareja/mundo'
    parent = 'main-400'
    weight = 3

  # main-500: Estilo de vida
  [[menu.main]]
    name = 'Estilo de vida'
    identifier = 'main-500'
    pageRef = ''
    weight = 5

  [[menu.main]]
    name = 'Cultura'
    identifier = 'main-500/1'
    pageRef = 'categories/cultura'
    parent = 'main-500'
    weight = 1

  [[menu.main]]
    name = 'Hoteles'
    identifier = 'main-500/2'
    pageRef = 'categories/hoteles'
    parent = 'main-500'
    weight = 2

  [[menu.main]]
    name = 'Gourmet'
    identifier = 'main-500/3'
    pageRef = 'categories/gourmet'
    parent = 'main-500'
    weight = 3

  [[menu.main]]
    name = 'Bienestar'
    identifier = 'main-500/4'
    pageRef = 'categories/bienestar'
    parent = 'main-500'
    weight = 4

  [[menu.main]]
    name = 'Compras'
    identifier = 'main-500/5'
    pageRef = 'categories/compras'
    parent = 'main-500'
    weight = 5

  [[menu.main]]
    name = 'Ocio'
    identifier = 'main-500/5'
    pageRef = 'categories/ocio'
    parent = 'main-500'
    weight = 6


  # main-600: Entre mujeres
  [[menu.main]]
    name = 'Entre mujeres'
    identifier = 'main-600'
    pageRef = ''
    weight = 6


  [[menu.main]]
    name = 'Mujeres Top'
    identifier = 'main-600/1'
    pageRef = 'categories/mujeres-top'
    parent = 'main-600'
    weight = 1

  [[menu.main]]
    name = 'Historias'
    identifier = 'main-600/2'
    pageRef = 'categories/historias'
    parent = 'main-600'
    weight = 2

  [[menu.main]]
    name = 'Equipo Etheria'
    identifier = 'main-600/3'
    pageRef = 'pagina de equipo!!'
    parent = 'main-600'
    weight = 3


  # Menu footer
  [[menu.footer]]
    name = 'Política de privacidad'
    identifier = 'footer-100'
    pageRef = 'pages/politica-de-privacidad'
    weight = 1

  [[menu.footer]]
    name = 'Política de cookies'
    identifier = 'footer-200'
    pageRef = 'pages/politica-de-cookies'
    weight = 2


[params]
  dateFormatLong = ":date_long"
  dateFormatShort = "02.01.2006"
  defaultPostCover = "https://placehold.co/1200x750"
  mainCategories = [
    "viajar-sola",
    "viajar-con-amigas",
    "viajar-en-pareja",
    "viajar-en-familia",
  ]
  otherCategories = [
    "inspiración",
    "cultura",
    "ocio",
    "gourmet",
    "bienestar",
    "compras",
  ]

  [params.easyads]
    section = "easyads"

  [params.gitinfo]
    repositoryUrl = "https://github.com/etheriamagazine/hugo-modules"
    branch = "main"
    contentRoot = "content"
