baseURL = 'https://example.org/'
title = 'Sky Theme'
summaryLength = 20

ignoreFiles = ['^banners/']
[outputs]
  home = ["html", "json"]

[build]
  [build.buildStats]
    enable = true

  [[build.cachebusters]]
    source = "layouts/.*"
    target = "css"

  [[build.cachebusters]]
    source = "assets/js/.*"
    target = "css"

  [[build.cachebusters]]
      source = "assets/notwatching/hugo_stats\\.json"
      target = "css"


[module]
  # imports
  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/jslibs/preact-bundle'

  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/jslibs/alpinejs'

  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/jslibs/minisearch'

  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/adroller'

  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/imgproxy'

  [[module.imports]]
    path = "github.com/etheriamagazine/hugo-modules/seo-tools/basic-seo"

  [[module.imports]]
    path = "github.com/etheriamagazine/hugo-modules/seo-tools/plausible-analytics"

  [[module.imports]]
    path = "github.com/etheriamagazine/hugo-modules/seo-tools/json-ld"


  # mounts
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
      source  = "hugo_stats.json"
      target = "assets/notwatching/hugo_stats.json"
      disableWatch = true
