

[module]
    
    [[module.mounts]]
        source = 'assets'
        target = 'assets'
    [[module.mounts]]
        source = 'layouts'      
        target = 'layouts'   
    [[module.mounts]]
        source = 'static'
        target = 'static'   
       
    [[module.imports]]
        path = 'github.com/etheriamagazine/hugo-modules/jslibs/preact-bundle'

    [[module.imports]]
        path = 'github.com/etheriamagazine/hugo-modules/jslibs/alpinejs'

    [[module.imports]]
        path = 'github.com/etheriamagazine/hugo-modules/jslibs/minisearch'

    [[module.imports]]
        path = 'github.com/etheriamagazine/hugo-modules/image-optimize'
