[module]

  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "static"
    target = "static"

  # sample content
  [[module.mounts]]
    source = "dev_content"
    target = "content"

  # sample content
  [[module.mounts]]
    source = "content"
    target = "content"

  # mount content adapter
  [[module.mounts]]
    source = "content/categories/_content.gotmpl"
    target = "content/categories/_content.gotmpl"

  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/notwatching/hugo_stats.json"
    disableWatch = true


[params]

  [params.gitinfo]
    repositoryUrl = "https://github.com/etheriamagazine/hugo-modules"
    contentRoot = "sky-theme/dev_content"
    # branch = "main"

  [params.reflink]
    errorOn404 = false

  [params.navigation]
    travelInterests = [
      "viajar-sola",
      "viajes-con-amigas",
      "viajes-romanticos",
      "viaje-en-familia",
      "viajes-urbanos",
      "viajes-cine",
      "viajes-ecoturismo",
      "viajes-gastronomicos",
    ]

    travelPlanning = [
      "mejores-restaurantes-gastronomia",
      "hoteles",
      "bienestar-belleza",
      "experiencias-viajeras",
      "regalos-compras-viajeras",
      "que-llevar-en-la-maleta",
      "mi-peor-viaje",
    ]

    plansAndCulture = [
      "planes-originales-para-mujeres",
      "exposiciones",
      "festivales",
      "libros-de-viajes",
      "parques-ocio",
      "visitas-guiadas",
      "de-un-vistazo",
      "viajes-48-horas",

    ]


  [params.imgproxy]
    enabled = true
    host = "https://imgp.etheriamagazine.com/"
    sourceStyle = "plain"

    [params.imgproxy.responsive]
      defaultSize = 900
      responsiveSizes = [600, 900, 1200]
      processingOptions = "rs:fit:%s"
      format = "avif"


  [params.plausible]
    enable = true
    domain = "etheriamagazine-com.fly.dev"

    proxy = true
    proxyPath = "/eu-compliance"

    [params.plausible.optional]
      local = true
      fileDownloads = true
      outboundLinks = true
      error404 = true
      customEvents = true

