baseURL = 'https://example.org/'
title = 'Sky Theme'
summaryLength = 20

ignoreFiles = ['^banners/']
[outputs]
  home = ["html", "json"]


[module]
  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/jslibs/preact-bundle'
  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/jslibs/alpinejs'
  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/jslibs/minisearch'
  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/adroller'
  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-modules/imgproxy'
  [[module.imports]]
    path = "github.com/etheriamagazine/hugo-modules/seo-tools/basic-seo"
  [[module.imports]]
    path = "github.com/etheriamagazine/hugo-modules/seo-tools/plausible-analytics"
  [[module.imports]]
    path = "github.com/etheriamagazine/hugo-modules/seo-tools/json-ld"
