

[module]
    
    [[module.imports]]
        path = 'github.com/etheriamagazine/hugo-modules/jslibs/preact-bundle'

    [[module.imports]]
        path = 'github.com/etheriamagazine/hugo-modules/jslibs/alpinejs'

    [[module.imports]]
        path = 'github.com/etheriamagazine/hugo-modules/jslibs/minisearch'

    [[module.imports]]
        path = 'github.com/etheriamagazine/hugo-modules/image-optimize'
